version: '3.9'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_db_task1:/var/lib/postgresql/data/
    env_file:
      - .env
    hostname: "postgres"

  backend:
    build:
      context: src/
      dockerfile: Backend.dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_db_task1: